M48
; DRILL file {KiCad (6.0.7)} date Sat Sep 24 00:10:23 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-24T00:10:23+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.4614Y-2.0079
X3.4614Y-3.7402
X6.4567Y-2.0079
X6.4567Y-3.7402
T0
M30
